name: Coverage

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
      - name: Get the Numbers
        run: echo """::set-env name=CODE_LINES::$( julia -v -e 'using Pkg; Pkg.add("Coverage"); using Coverage; @show get_summary(process_folder())' )"""
      - name: Create Coverage-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 90e476e8365403823681230c8d99fd38
          filename: loc.json
          label: Coverage
          message: ${{ env.CODE_LINES }}
          color: green
          
